import { Injectable } from '@angular/core';
import { Recipe } from '../models/recipe.model';

@Injectable ({
  providedIn: 'root'
})
export class RecipeService {
  getRecipes(): Recipe[] {
    return [
      {
        id: 1,
        title: 'Nasi Uduk',
        category: 'Makanan',
        item1: '300 gr beras',
        item2: '30 ml santan kental',
        item3: '+-420 ml air',
        item4: '1 sdt garam',
        item5: '2 lembar salam',
        item6: '1 lembar daun pandan',
        item7: '1 batang serai',
        item8: '1 ruas lengkuas',
        item9: '1/2 sdt rempah bubuk jahe lemonilo',
        item10: '',
        desc1: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc2: 'Tambahkan Rempah Bubuk Jahe Lemonilo, daun salam, santan, daun pandan, serai, lengkuas, garam, dan gula',
        desc3: 'Tambahkan air sambil diaduk rata. Kemudian masak dengan rice cooker',
        desc4: '',
        desc5: '',
        desc6: '',
        desc7: '',
        desc8: '',
        desc9: '',
        desc10: '',
        image: 'assets/images/recipes/nasi-uduk.png',
        description:
          'In addition to the freshet seafood, there are corn, cilantro, and tomatoes: their first became mayonnise.',
      },
      {
        id: 2,
        title: 'Jus Jeruk',
        category: 'Minuman',
        item1: 'beras',
        item2: 'santan',
        item3: 'beras',
        item4: 'santan',
        item5: 'beras',
        item6: 'santan',
        item7: 'beras',
        item8: 'santan',
        item9: 'beras',
        item10: 'santan',
        desc1: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc2: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc3: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc4: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc5: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc6: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc7: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc8: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc9: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc10: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        image: 'assets/images/recipes/jus-jeruk.png',
        description:
          'In addition to the freshet seafood, there are corn, cilantro, and tomatoes: their first became mayonnise.',
      },
      {
        id: 3,
        title: 'Sambal Terasi',
        category: 'Lainnya',
        item1: 'beras',
        item2: 'santan',
        item3: 'beras',
        item4: 'santan',
        item5: 'beras',
        item6: 'santan',
        item7: 'beras',
        item8: 'santan',
        item9: 'beras',
        item10: 'santan',
        desc1: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc2: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc3: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc4: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc5: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc6: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc7: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc8: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc9: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc10: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        image: 'assets/images/recipes/sambal-terasi.png',
        description:
          'In addition to the freshet seafood, there are corn, cilantro, and tomatoes: their first became mayonnise.',
      },
      {
        id: 4,
        title: 'Pizza',
        category: 'Makanan',
        item1: 'beras',
        item2: 'santan',
        item3: 'beras',
        item4: 'santan',
        item5: 'beras',
        item6: 'santan',
        item7: 'beras',
        item8: 'santan',
        item9: 'beras',
        item10: 'santan',
        desc1: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc2: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc3: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc4: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc5: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc6: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc7: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc8: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc9: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc10: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        image: 'assets/images/recipes/pizza.png',
        description:
          'In addition to the freshet seafood, there are corn, cilantro, and tomatoes: their first became mayonnise.',
      },
      {
        id: 5,
        title: 'Breakfast',
        category: 'Makanan',
        item1: 'beras',
        item2: 'santan',
        item3: 'beras',
        item4: 'santan',
        item5: 'beras',
        item6: 'santan',
        item7: 'beras',
        item8: 'santan',
        item9: 'beras',
        item10: 'santan',
        desc1: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc2: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc3: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc4: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc5: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc6: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc7: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc8: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc9: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc10: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        image: 'assets/images/recipes/scott-ish-breakfast.png',
        description:
          'In addition to the freshet seafood, there are corn, cilantro, and tomatoes: their first became mayonnise.',
      },
      {
        id: 6,
        title: 'Tambi',
        category: 'Makanan',
        item1: 'beras',
        item2: 'santan',
        item3: 'beras',
        item4: 'santan',
        item5: 'beras',
        item6: 'santan',
        item7: 'beras',
        item8: 'santan',
        item9: 'beras',
        item10: 'santan',
        desc1: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc2: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc3: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc4: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc5: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc6: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc7: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc8: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc9: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        desc10: 'Masukkan beras yang sudah dicuci ke dalam rice cooker',
        image: 'assets/images/recipes/tambi.png',
        description:
          'In addition to the freshet seafood, there are corn, cilantro, and tomatoes: their first became mayonnise.',
      },
    ];
  }

  getRecipe(id: number): Recipe {
    return this.getRecipes().find((food) => food.id === id);
  }
}
